# Automatically generated file: DO NOT EDIT!
#
BUILD_ROOT="/builddir/build/BUILD/mgmt-rbt_sh-0.1/mgmt/framework"
export BUILD_ROOT
BUILD_SCM_SYSTEM="unknown"
export BUILD_SCM_SYSTEM
BUILD_SCM_REPOS_ROOT="unknown"
export BUILD_SCM_REPOS_ROOT
BUILD_SCM_REPOS_NAME="unknown"
export BUILD_SCM_REPOS_NAME
BUILD_SCM_REPOS_BRANCH="unknown"
export BUILD_SCM_REPOS_BRANCH
BUILD_TYPE="dev"
export BUILD_TYPE
BUILD_HOST_MACHINE="bannow-worker6.lab.nbttech.com"
export BUILD_HOST_MACHINE
BUILD_HOST_MACHINE_SHORT="bannow-worker6"
export BUILD_HOST_MACHINE_SHORT
BUILD_HOST_USER="mockbuild"
export BUILD_HOST_USER
BUILD_HOST_OS="LINUX"
export BUILD_HOST_OS
BUILD_HOST_OS_LC="linux"
export BUILD_HOST_OS_LC
BUILD_HOST_PLATFORM="LINUX_SL"
export BUILD_HOST_PLATFORM
BUILD_HOST_PLATFORM_LC="linux_sl"
export BUILD_HOST_PLATFORM_LC
BUILD_HOST_PLATFORM_VERSION="6"
export BUILD_HOST_PLATFORM_VERSION
BUILD_HOST_PLATFORM_VERSION_LC="6"
export BUILD_HOST_PLATFORM_VERSION_LC
BUILD_HOST_PLATFORM_FULL="LINUX_SL_6"
export BUILD_HOST_PLATFORM_FULL
BUILD_HOST_PLATFORM_FULL_LC="linux_sl_6"
export BUILD_HOST_PLATFORM_FULL_LC
BUILD_HOST_ARCH="X86_64"
export BUILD_HOST_ARCH
BUILD_HOST_ARCH_LC="x86_64"
export BUILD_HOST_ARCH_LC
BUILD_HOST_CPU="X86_64"
export BUILD_HOST_CPU
BUILD_HOST_CPU_LC="x86_64"
export BUILD_HOST_CPU_LC
BUILD_TARGET_OS="LINUX"
export BUILD_TARGET_OS
BUILD_TARGET_OS_LC="linux"
export BUILD_TARGET_OS_LC
BUILD_TARGET_PLATFORM="LINUX_SL"
export BUILD_TARGET_PLATFORM
BUILD_TARGET_PLATFORM_LC="linux_sl"
export BUILD_TARGET_PLATFORM_LC
BUILD_TARGET_PLATFORM_VERSION="6"
export BUILD_TARGET_PLATFORM_VERSION
BUILD_TARGET_PLATFORM_VERSION_LC="6"
export BUILD_TARGET_PLATFORM_VERSION_LC
BUILD_TARGET_PLATFORM_FULL="LINUX_SL_6"
export BUILD_TARGET_PLATFORM_FULL
BUILD_TARGET_PLATFORM_FULL_LC="linux_sl_6"
export BUILD_TARGET_PLATFORM_FULL_LC
BUILD_TARGET_ARCH="X86_64"
export BUILD_TARGET_ARCH
BUILD_TARGET_ARCH_LC="x86_64"
export BUILD_TARGET_ARCH_LC
BUILD_TARGET_CPU="X86_64"
export BUILD_TARGET_CPU
BUILD_TARGET_CPU_LC="x86_64"
export BUILD_TARGET_CPU_LC
BUILD_PROD_PRODUCT="RBT_SH"
export BUILD_PROD_PRODUCT
BUILD_PROD_PRODUCT_LC="rbt_sh"
export BUILD_PROD_PRODUCT_LC
BUILD_PROD_CUSTOMER="RBT"
export BUILD_PROD_CUSTOMER
BUILD_PROD_CUSTOMER_LC="rbt"
export BUILD_PROD_CUSTOMER_LC
BUILD_PROD_UPTIME_BINARY="sport"
export BUILD_PROD_UPTIME_BINARY
BUILD_PROD_ID="SH"
export BUILD_PROD_ID
BUILD_PROD_ID_LC="sh"
export BUILD_PROD_ID_LC
BUILD_PROD_MODELS="1 1050 2050 5050 6050 0501 0601 7050 0701 CX255 CX1555 CX5055 CX7055 CX8055 EX560 EX760 EX1160 EX1260 EX1360 Virtual CloudVirtual CloudAWS VCX "
export BUILD_PROD_MODELS
BUILD_PROD_MODELS_32="150 250 550 CX555 CX755"
export BUILD_PROD_MODELS_32
BUILD_PROD_MODELS_64="1 1050 2050 5050 6050 0501 0601 7050 0701 CX255 CX1555 CX5055 CX7055 CX8055 EX560 EX760 EX1160 EX1260 EX1360 Virtual CloudVirtual CloudAWS VCX "
export BUILD_PROD_MODELS_64
BUILD_PROD_FEATURES_ENABLED=" ENCRYPTION SCHED CRLD SSL_SERVER_CERT_POOL NTP_CLIENT DHCP_CLIENT AAA RADIUS TACACS XINETD TELNETD CMC_CLIENT FG_CLIENT WEB_VER_2 MULTI_USER CLI_VER_2 WCCP_SUPPORT POSTGRES"
export BUILD_PROD_FEATURES_ENABLED
BUILD_PROD_FEATURES_ENABLED_LC="encryption sched crld ssl_server_cert_pool ntp_client dhcp_client aaa radius tacacs xinetd telnetd cmc_client fg_client web_ver_2 multi_user cli_ver_2 wccp_support postgres"
export BUILD_PROD_FEATURES_ENABLED_LC
BUILD_FLASH_SUPPORT="1"
export BUILD_FLASH_SUPPORT
BUILD_1050U_SUPPORT="1"
export BUILD_1050U_SUPPORT
BUILD_1050RAIDUP_SUPPORT="1"
export BUILD_1050RAIDUP_SUPPORT
BUILD_5050L_SUPPORT="1"
export BUILD_5050L_SUPPORT
BUILD_8150_SV_ON_VAR_SUPPORT="1"
export BUILD_8150_SV_ON_VAR_SUPPORT
BUILD_MOD_100_SUPPORT="1"
export BUILD_MOD_100_SUPPORT
BUILD_V150M_SUPPORT="1"
export BUILD_V150M_SUPPORT
BUILD_CB_SV_ON_VAR_SUPPORT="1"
export BUILD_CB_SV_ON_VAR_SUPPORT
BUILD_PROD_FEATURE_ENCRYPTION="1"
export BUILD_PROD_FEATURE_ENCRYPTION
BUILD_PROD_FEATURE_SCHED="1"
export BUILD_PROD_FEATURE_SCHED
BUILD_PROD_FEATURE_CRLD="1"
export BUILD_PROD_FEATURE_CRLD
BUILD_PROD_FEATURE_SSL_SERVER_CERT_POOL="1"
export BUILD_PROD_FEATURE_SSL_SERVER_CERT_POOL
BUILD_PROD_FEATURE_NTP_CLIENT="1"
export BUILD_PROD_FEATURE_NTP_CLIENT
BUILD_PROD_FEATURE_DHCP_CLIENT="1"
export BUILD_PROD_FEATURE_DHCP_CLIENT
BUILD_PROD_FEATURE_AAA="1"
export BUILD_PROD_FEATURE_AAA
BUILD_PROD_FEATURE_RADIUS="1"
export BUILD_PROD_FEATURE_RADIUS
BUILD_PROD_FEATURE_TACACS="1"
export BUILD_PROD_FEATURE_TACACS
BUILD_PROD_FEATURE_XINETD="1"
export BUILD_PROD_FEATURE_XINETD
BUILD_PROD_FEATURE_TELNETD="1"
export BUILD_PROD_FEATURE_TELNETD
BUILD_PROD_FEATURE_CMC_CLIENT="1"
export BUILD_PROD_FEATURE_CMC_CLIENT
BUILD_PROD_FEATURE_FG_CLIENT="1"
export BUILD_PROD_FEATURE_FG_CLIENT
BUILD_PROD_FEATURE_WEB_VER_2="1"
export BUILD_PROD_FEATURE_WEB_VER_2
BUILD_PROD_FEATURE_MULTI_USER="1"
export BUILD_PROD_FEATURE_MULTI_USER
BUILD_PROD_FEATURE_CLI_VER_2="1"
export BUILD_PROD_FEATURE_CLI_VER_2
BUILD_PROD_FEATURE_WCCP_SUPPORT="1"
export BUILD_PROD_FEATURE_WCCP_SUPPORT
BUILD_PROD_FEATURE_POSTGRES="1"
export BUILD_PROD_FEATURE_POSTGRES
BUILD_ID="#19"
export BUILD_ID
BUILD_DATE="2013-09-16 08:27:19"
export BUILD_DATE
BUILD_NUMBER="19"
export BUILD_NUMBER
BUILD_PROD_NAME="rbt_sh"
export BUILD_PROD_NAME
BUILD_PROD_VERSION="rbt_sh 8.5.0 #19 2013-09-16 08:27:19 x86_64 uuid:f6c2bce0-0bf6-4e1b-93f1-c72bb6f0270c"
export BUILD_PROD_VERSION
BUILD_BANNOW_BUILD_UUID="f6c2bce0-0bf6-4e1b-93f1-c72bb6f0270c"
export BUILD_BANNOW_BUILD_UUID
BUILD_PROD_RELEASE="8.5.0"
export BUILD_PROD_RELEASE
# Automatically generated file: DO NOT EDIT!
#
BANNOW_TRACKING_NUMBER_MGMT_FWK=1.0,2103.0,1.0,186.0
export BANNOW_TRACKING_NUMBER_MGMT_FWK
BANNOW_TRACKING_NUMBER_SPORT=1.0,2234.0,3.0
export BANNOW_TRACKING_NUMBER_SPORT
