# Automatically generated file: DO NOT EDIT!
#
IL_LAYOUT=FLASHRRDM
export IL_LAYOUT
IL_KERNEL_TYPE=smp
export IL_KERNEL_TYPE
IL_LO_FLASHRRDM_TARGET_DISK1_DEV=/dev/flash0
export IL_LO_FLASHRRDM_TARGET_DISK1_DEV
