function FileData_Pairs(x)
{
x.t("appendix","steelhead");
x.t("appendix","includes");
x.t("appendix","provides");
x.t("easy","management");
x.t("integration","nto");
x.t("appliance","enterprise");
x.t("appliance","mib");
x.t("steelhead","appliance");
x.t("steelhead","enterprise");
x.t("steelhead","appliances");
x.t("sections","accessing");
x.t("includes","following");
x.t("enterprise","mib");
x.t("network","management");
x.t("provides","reference");
x.t("allow","easy");
x.t("straightforward","integration");
x.t("accessing","steelhead");
x.t("reference","steelhead");
x.t("existing","network");
x.t("appliances","straightforward");
x.t("tools","allow");
x.t("systems","appendix");
x.t("nto","existing");
x.t("mib","appendix");
x.t("mib","steelhead");
x.t("mib","snmp");
x.t("snmp","traps");
x.t("management","steelhead");
x.t("management","systems");
x.t("following","sections");
x.t("traps","tools");
}
