function FileData_Pairs(x)
{
x.t("email","settings");
x.t("announcements","configuring");
x.t("describes","configure");
x.t("administrator","settings");
x.t("time","configuring");
x.t("sections","configuring");
x.t("includes","sections");
x.t("monitored","ports");
x.t("configuring","email");
x.t("configuring","monitored");
x.t("configuring","alarm");
x.t("configuring","date");
x.t("configuring","snmp");
x.t("configuring","system");
x.t("configuring","log");
x.t("features","assist");
x.t("assist","system");
x.t("settings","configuring");
x.t("settings","chapter");
x.t("settings","setting");
x.t("ports","configuring");
x.t("chapter","describes");
x.t("chapter","configuring");
x.t("alarm","settings");
x.t("configure","features");
x.t("administration","includes");
x.t("date","time");
x.t("snmp","settings");
x.t("system","administrator");
x.t("system","administration");
x.t("setting","announcements");
x.t("log","settings");
}
