#!/bin/bash
#
# chkconfig: 345 16 15
# description: ESPd provides a communication path with HP Procurve Switches
# processname: espd
# pidfile: /var/run/espd.pid
# Source function library.
. /etc/init.d/functions

prog=$"ESP daemon"

start() {
    echo -n $"Starting $prog: "
    ulimit -S -c 0 >/dev/null 2>&1
    daemon espd
    RETVAL=$?
    echo
    [ "$RETVAL" -eq 0 ] && touch /var/lock/subsys/espd
    return $RETVAL
}

stop() {
    echo -n $"Shutting down $prog: "
    if [ ! -e /var/lock/subsys/espd ]; then
        echo -n $"cannot stop espd: espd is not running."
        failure $"cannot stop espd: espd is not running."
        echo
        return 1;
	fi
    killproc espd
    RETVAL=$?
    echo
    [ "$RETVAL" -eq 0 ] && rm -f /var/lock/subsys/espd
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  status)
	status espd
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

