#!/bin/sh

# Version 1.01
# ------------

# Script to execute the "linttylog.bin" binary for LINUX ONLY
# This script opens a node at run time. It gets the major
# no of the megadev and then opens a node with the major number.
# If the node is already present, it removes the node first
# and then creates a fresh node.
# The binary "linttylog.bin" must be present in the same directoy
# where the script is invoked from.

# Get the major number of the megadev ioctl node
MAJOR=`grep megadev /proc/devices|awk '{print $1}'`

if [ ! x$MAJOR = x ]
then
	# major device number found
	rm -f /dev/megadev0 	# remove if already there, ignore if not.
	mknod /dev/megadev0  c $MAJOR 0
fi

# RedHat 8.0 specific changes : as unicode is default
# on RH8.0 release
#------------
if [ `/sbin/consoletype` = vt ]
then
  grep -q unicode_start /etc/profile.d/lang.sh && unicode_stop && setfont
fi

OLD_TERM=$TERM
case  $TERM in
     "xterm" | "linux") 
	;;
     *) export TERM=linux;;
esac

# Execute linttylog code
/usr/sbin/linttylog.bin $*
ret=$?

# RedHat 8.0 specific changes
#----------------------------
export TERM=$OLD_TERM
if [ `/sbin/consoletype` = vt ]
then
  grep -q unicode_start /etc/profile.d/lang.sh && unicode_start && setfont
fi
exit $ret

