function FileData_Pairs(x)
{
x.t("describes","configure");
x.t("ssl","secure");
x.t("ssl","support");
x.t("ssl","cipher");
x.t("ssl","main");
x.t("ssl","server");
x.t("secure","inner");
x.t("secure","peers");
x.t("support","includes");
x.t("sections","configuring");
x.t("channel","configuring");
x.t("channel","chapter");
x.t("advanced","ssl");
x.t("includes","following");
x.t("crl","management");
x.t("configuring","ssl");
x.t("configuring","secure");
x.t("configuring","advanced");
x.t("configuring","crl");
x.t("settings","configuring");
x.t("inner","channel");
x.t("certificates","certificate");
x.t("certificate","authorities");
x.t("cipher","settings");
x.t("chapter","describes");
x.t("chapter","configuring");
x.t("authorities","configuring");
x.t("peers","configuring");
x.t("main","settings");
x.t("configure","ssl");
x.t("following","sections");
x.t("management","configuring");
x.t("server","certificates");
}
