function FileData_Pairs(x)
{
x.t("console","home");
x.t("console","getting");
x.t("console","includes");
x.t("console","chapter");
x.t("console","following");
x.t("console","using");
x.t("describes","connect");
x.t("home","page");
x.t("interface","reference");
x.t("sections","connecting");
x.t("navigating","management");
x.t("getting","help");
x.t("details","riverbed");
x.t("includes","following");
x.t("overview","management");
x.t("navigate","management");
x.t("configuring","monitoring");
x.t("tasks","details");
x.t("perform","configuring");
x.t("connecting","management");
x.t("command-line","interface");
x.t("chapter","overview");
x.t("section","describes");
x.t("reference","manual");
x.t("cli","perform");
x.t("page","navigating");
x.t("help","note");
x.t("monitoring","tasks");
x.t("prefer","cli");
x.t("note","prefer");
x.t("riverbed","command-line");
x.t("management","console");
x.t("following","sections");
x.t("following","section");
x.t("using","management");
x.t("connect","navigate");
}
