function FileData_Pairs(x)
{
x.t("label","list");
x.t("appendix","steelhead");
x.t("create","port");
x.t("appliance","multiple");
x.t("appliance","ports");
x.t("steelhead","appliance");
x.t("video","conferencing");
x.t("1720-1727","3230-3253");
x.t("multiple","ports");
x.t("want","exclude");
x.t("list","ports");
x.t("cisco","iptel");
x.t("summarizes","ports");
x.t("polycomm","video");
x.t("conferencing","1503");
x.t("exclude","create");
x.t("optimization","steelhead");
x.t("ports","appendix");
x.t("ports","want");
x.t("ports","polycomm");
x.t("ports","commonly");
x.t("ports","section");
x.t("ports","application");
x.t("1503","1720-1727");
x.t("commonly","excluded");
x.t("iptel","2000");
x.t("section","summarizes");
x.t("excluded","optimization");
x.t("excluded","ports");
x.t("5060","cisco");
x.t("application","ports");
x.t("port","label");
x.t("3230-3253","5060");
}
