function FileData_Pairs(x)
{
x.t("enabling","peering");
x.t("describes","enable");
x.t("peering","configuring");
x.t("peering","rules");
x.t("peering","configure");
x.t("regular","enhanced");
x.t("sections","regular");
x.t("includes","following");
x.t("discovery","configuring");
x.t("configuring","peering");
x.t("configuring","optimization");
x.t("features","enabling");
x.t("optimization","features");
x.t("automatic","discovery");
x.t("chapter","configuring");
x.t("section","describes");
x.t("enable","peering");
x.t("rules","enabling");
x.t("rules","includes");
x.t("rules","chapter");
x.t("rules","section");
x.t("configure","peering");
x.t("enhanced","automatic");
x.t("following","sections");
}
