function FileData_Pairs(x)
{
x.t("files","download");
x.t("files","chapter");
x.t("files","downloading");
x.t("user","logs");
x.t("user","log");
x.t("download","user");
x.t("download","display");
x.t("download","page");
x.t("problems","download");
x.t("display","user");
x.t("viewing","reports");
x.t("activity","troubleshoot");
x.t("chapter","viewing");
x.t("reports","logs");
x.t("reports","diagnostics");
x.t("logs","user");
x.t("logs","download");
x.t("logs","monitor");
x.t("logs","choose");
x.t("logs","downloading");
x.t("diagnostics","user");
x.t("page","download");
x.t("monitor","system");
x.t("choose","reports");
x.t("downloading","user");
x.t("downloading","log");
x.t("troubleshoot","problems");
x.t("system","activity");
x.t("log","files");
}
