function FileData_Pairs(x)
{
x.t("interfaces","modifying");
x.t("properties","ran");
x.t("describes","view");
x.t("describes","configure");
x.t("wizard","section");
x.t("interface","settings");
x.t("initially","properties");
x.t("sections","modifying");
x.t("needed","includes");
x.t("includes","following");
x.t("network","interface");
x.t("settings","initially");
x.t("settings","needed");
x.t("settings","modifying");
x.t("settings","chapter");
x.t("ran","installation");
x.t("base","interfaces");
x.t("modifying","base");
x.t("modifying","in-path");
x.t("modifying","host");
x.t("modifying","general");
x.t("chapter","describes");
x.t("chapter","modifying");
x.t("section","describes");
x.t("in-path","interfaces");
x.t("view","modify");
x.t("host","network");
x.t("host","settings");
x.t("configure","host");
x.t("following","sections");
x.t("installation","wizard");
x.t("general","host");
x.t("modify","settings");
}
