# Automatically generated file: DO NOT EDIT!
#
BUILD_ROOT="/work/flamebox/mgmt-build-774/mgmt/framework"
export BUILD_ROOT
BUILD_SCM_SYSTEM="svn"
export BUILD_SCM_SYSTEM
BUILD_SCM_REPOS_ROOT="svn://svn/mgmt/branches/malta_529_fix_branch"
export BUILD_SCM_REPOS_ROOT
BUILD_SCM_REPOS_NAME="svn://svn/mgmt"
export BUILD_SCM_REPOS_NAME
BUILD_SCM_REPOS_BRANCH="branches/malta_529_fix_branch"
export BUILD_SCM_REPOS_BRANCH
BUILD_DATE="2012-09-25 16:53:55"
export BUILD_DATE
BUILD_TYPE="numbered"
export BUILD_TYPE
BUILD_NUMBER="529_3"
export BUILD_NUMBER
BUILD_ID="#529_3"
export BUILD_ID
BUILD_HOST_MACHINE="poznan.lab.nbttech.com"
export BUILD_HOST_MACHINE
BUILD_HOST_MACHINE_SHORT="poznan"
export BUILD_HOST_MACHINE_SHORT
BUILD_HOST_USER="root"
export BUILD_HOST_USER
BUILD_HOST_OS="LINUX"
export BUILD_HOST_OS
BUILD_HOST_OS_LC="linux"
export BUILD_HOST_OS_LC
BUILD_HOST_PLATFORM="LINUX_CENTOS"
export BUILD_HOST_PLATFORM
BUILD_HOST_PLATFORM_LC="linux_centos"
export BUILD_HOST_PLATFORM_LC
BUILD_HOST_PLATFORM_VERSION="48"
export BUILD_HOST_PLATFORM_VERSION
BUILD_HOST_PLATFORM_VERSION_LC="48"
export BUILD_HOST_PLATFORM_VERSION_LC
BUILD_HOST_PLATFORM_FULL="LINUX_CENTOS_48"
export BUILD_HOST_PLATFORM_FULL
BUILD_HOST_PLATFORM_FULL_LC="linux_centos_48"
export BUILD_HOST_PLATFORM_FULL_LC
BUILD_HOST_ARCH="X86_64"
export BUILD_HOST_ARCH
BUILD_HOST_ARCH_LC="x86_64"
export BUILD_HOST_ARCH_LC
BUILD_HOST_CPU="X86_64"
export BUILD_HOST_CPU
BUILD_HOST_CPU_LC="x86_64"
export BUILD_HOST_CPU_LC
BUILD_TARGET_OS="LINUX"
export BUILD_TARGET_OS
BUILD_TARGET_OS_LC="linux"
export BUILD_TARGET_OS_LC
BUILD_TARGET_PLATFORM="LINUX_CENTOS"
export BUILD_TARGET_PLATFORM
BUILD_TARGET_PLATFORM_LC="linux_centos"
export BUILD_TARGET_PLATFORM_LC
BUILD_TARGET_PLATFORM_VERSION="42"
export BUILD_TARGET_PLATFORM_VERSION
BUILD_TARGET_PLATFORM_VERSION_LC="42"
export BUILD_TARGET_PLATFORM_VERSION_LC
BUILD_TARGET_PLATFORM_FULL="LINUX_CENTOS_42"
export BUILD_TARGET_PLATFORM_FULL
BUILD_TARGET_PLATFORM_FULL_LC="linux_centos_42"
export BUILD_TARGET_PLATFORM_FULL_LC
BUILD_TARGET_ARCH="X86_64"
export BUILD_TARGET_ARCH
BUILD_TARGET_ARCH_LC="x86_64"
export BUILD_TARGET_ARCH_LC
BUILD_TARGET_CPU="X86_64"
export BUILD_TARGET_CPU
BUILD_TARGET_CPU_LC="x86_64"
export BUILD_TARGET_CPU_LC
BUILD_PROD_PRODUCT="RBT_SH"
export BUILD_PROD_PRODUCT
BUILD_PROD_PRODUCT_LC="rbt_sh"
export BUILD_PROD_PRODUCT_LC
BUILD_PROD_CUSTOMER="RBT"
export BUILD_PROD_CUSTOMER
BUILD_PROD_CUSTOMER_LC="rbt"
export BUILD_PROD_CUSTOMER_LC
BUILD_PROD_UPTIME_BINARY="sport"
export BUILD_PROD_UPTIME_BINARY
BUILD_PROD_ID="SH"
export BUILD_PROD_ID
BUILD_PROD_ID_LC="sh"
export BUILD_PROD_ID_LC
BUILD_PROD_NAME="rbt_sh"
export BUILD_PROD_NAME
BUILD_PROD_RELEASE="7.0.5"
export BUILD_PROD_RELEASE
BUILD_PROD_VERSION="rbt_sh 7.0.5 #529_3 2012-09-25 16:53:55 x86_64 root@poznan:svn://svn/mgmt/branches/malta_529_fix_branch"
export BUILD_PROD_VERSION
BUILD_PROD_MODELS="1 1050 2050 5050 6050 0501 0601 7050 0701 260 560 R560 1060 R1060 CX1555 CX5055 CX7055 EX560 EX760 EX1160 EX1260 Virtual CloudAWS CloudVirtual "
export BUILD_PROD_MODELS
BUILD_PROD_MODELS_32="150 250 550 CX255 CX555 CX755"
export BUILD_PROD_MODELS_32
BUILD_PROD_MODELS_64="1 1050 2050 5050 6050 0501 0601 7050 0701 260 560 R560 1060 R1060 CX1555 CX5055 CX7055 EX560 EX760 EX1160 EX1260 Virtual CloudAWS CloudVirtual "
export BUILD_PROD_MODELS_64
BUILD_PROD_FEATURES_ENABLED=" ENCRYPTION SCHED CRLD SSL_SERVER_CERT_POOL NTP_CLIENT DHCP_CLIENT AAA RADIUS TACACS XINETD TELNETD CMC_CLIENT FG_CLIENT WEB_VER_2 MULTI_USER CLI_VER_2 WCCP_SUPPORT ALARMD"
export BUILD_PROD_FEATURES_ENABLED
BUILD_PROD_FEATURES_ENABLED_LC="encryption sched crld ssl_server_cert_pool ntp_client dhcp_client aaa radius tacacs xinetd telnetd cmc_client fg_client web_ver_2 multi_user cli_ver_2 wccp_support alarmd"
export BUILD_PROD_FEATURES_ENABLED_LC
BUILD_FLASH_SUPPORT="1"
export BUILD_FLASH_SUPPORT
BUILD_1050U_SUPPORT="1"
export BUILD_1050U_SUPPORT
BUILD_1050RAIDUP_SUPPORT="1"
export BUILD_1050RAIDUP_SUPPORT
BUILD_5050L_SUPPORT="1"
export BUILD_5050L_SUPPORT
BUILD_8150_SV_ON_VAR_SUPPORT="1"
export BUILD_8150_SV_ON_VAR_SUPPORT
BUILD_MOD_100_SUPPORT="1"
export BUILD_MOD_100_SUPPORT
BUILD_V150M_SUPPORT="1"
export BUILD_V150M_SUPPORT
BUILD_PROD_RIOS_VER=""
export BUILD_PROD_RIOS_VER=""
BUILD_PROD_GRANITE_VER=""
export BUILD_PROD_GRANITE_VER=""
BUILD_PROD_FEATURE_ENCRYPTION="1"
export BUILD_PROD_FEATURE_ENCRYPTION
BUILD_PROD_FEATURE_SCHED="1"
export BUILD_PROD_FEATURE_SCHED
BUILD_PROD_FEATURE_CRLD="1"
export BUILD_PROD_FEATURE_CRLD
BUILD_PROD_FEATURE_SSL_SERVER_CERT_POOL="1"
export BUILD_PROD_FEATURE_SSL_SERVER_CERT_POOL
BUILD_PROD_FEATURE_NTP_CLIENT="1"
export BUILD_PROD_FEATURE_NTP_CLIENT
BUILD_PROD_FEATURE_DHCP_CLIENT="1"
export BUILD_PROD_FEATURE_DHCP_CLIENT
BUILD_PROD_FEATURE_AAA="1"
export BUILD_PROD_FEATURE_AAA
BUILD_PROD_FEATURE_RADIUS="1"
export BUILD_PROD_FEATURE_RADIUS
BUILD_PROD_FEATURE_TACACS="1"
export BUILD_PROD_FEATURE_TACACS
BUILD_PROD_FEATURE_XINETD="1"
export BUILD_PROD_FEATURE_XINETD
BUILD_PROD_FEATURE_TELNETD="1"
export BUILD_PROD_FEATURE_TELNETD
BUILD_PROD_FEATURE_CMC_CLIENT="1"
export BUILD_PROD_FEATURE_CMC_CLIENT
BUILD_PROD_FEATURE_FG_CLIENT="1"
export BUILD_PROD_FEATURE_FG_CLIENT
BUILD_PROD_FEATURE_WEB_VER_2="1"
export BUILD_PROD_FEATURE_WEB_VER_2
BUILD_PROD_FEATURE_MULTI_USER="1"
export BUILD_PROD_FEATURE_MULTI_USER
BUILD_PROD_FEATURE_CLI_VER_2="1"
export BUILD_PROD_FEATURE_CLI_VER_2
BUILD_PROD_FEATURE_WCCP_SUPPORT="1"
export BUILD_PROD_FEATURE_WCCP_SUPPORT
BUILD_PROD_FEATURE_ALARMD="1"
export BUILD_PROD_FEATURE_ALARMD
