#!/bin/sh
#
# This script will be executed *after* all the other init scripts.
# You can put your own initialization stuff in here if you don't
# want to do the full Sys V style init stuff.

touch /var/lock/subsys/local

if [ -f "/var/tmp/rfut.log" ]; then
        echo "trying to put rfut log into messages"
        cat /var/tmp/rfut.log >> /var/log/messages
        rm -f /var/tmp/rfut.log
        sync
fi

/sbin/kernel_crashdump.sh &

