#!/bin/bash
#
# oom_profile      Starts oom_profile.sh
#
#
# chkconfig: 345 60 40
# description: gathers information useful for diagnosing out of memory conditions
### BEGIN INIT INFO
# Provides: $oom_profile
### END INIT INFO


# Source function library.
. /etc/rc.d/init.d/functions

OOM_PROFILE=/sbin/oom_profile.sh

[ -f "$OOM_PROFILE" ] || exit 0

RETVAL=0

umask 077

start() {
    echo -n $"Starting oom_profile: "
    "$OOM_PROFILE" &
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    echo -n $"Shutting down softwatch: "
    killproc "$OOM_PROFILE"
    echo
    RETVAL=$?
    return $RETVAL
}
rhstatus() {
    status "$SOFTWATCH"
}

restart() {
    stop
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit $RETVAL
